### ISSUE TITLE
Got Nginx.Accepted-Connections" became not supported: Received value [sh: /usr/lib/zabbix/externalscripts/getNginxInfo.py

### ISSUE THREAD

**Issue by BinWu1989** [vicendominguez/nginx-zabbix-template#10]
@vicendominguez Hi ,Could you kindly give me some help for monitoring the nginx using zabbix 3.2? After set the zabbix_agent.conf in your way , I got the below issue when I check the server log 
![image](https://cloud.githubusercontent.com/assets/15190107/20264522/eaa666a6-aaa6-11e6-8c45-68bd58c5e76a.png),

Below is the setting I used in the zabbix_agent.conf:

![image](https://cloud.githubusercontent.com/assets/15190107/20264568/2aff9b50-aaa7-11e6-9413-d238b9cb82b7.png)

Thanks

**Comment by big-loser** [comment]
1、你先尝试在zabbix_agent 端是否能够正常运行 getnginxinfo.py 这个脚本 。
2、你的nginx是否代开了nginx_status功能模块

**Comment by BinWu1989** [comment]
谢谢回复啊，这些都是正常的，最后发现是谷歌云服务器的问题，权限设置的太死了
