### ISSUE TITLE
Broken metrics when any metric reached 9 digits

### ISSUE THREAD

**Issue by vitargelo** [vicendominguez/nginx-zabbix-template#13]
You have the regexp in the getNginxInfo.py

`buffer = re.findall(r'\d{1,8}', result.read())`

When nginx running a long time and/or on high load servers the (server accepts handled requests) metrics can reach more than 8 digits number and the 9th digit will be parsed as next match and all metrics will be broken. It is better to set regexp to unlimited digits.

`buffer = re.findall(r'\d{1,}', result.read())`

**Comment by vicendominguez** [comment]
late but thx mate... not tested. No time. I hope it works.
